### ISSUE TITLE
Feature Request: Add version flag

### ISSUE THREAD

**Issue by dan-snelson** [brunerd/jpt#1]
Happy Thursday, @brunerd!

First, thanks for all your hard work on `jpt`.

While the version _is_ displayed when using `jpt -h`, it'd be nice to have a `-v` or `--version` flag which would return just `1.0.0` (i.e., for a Jamf Pro Extension Attribute).

**Comment by dan-snelson** [comment]
Issue No. 1 ?!?

**Comment by PicoMitchell** [comment]
If you're interested in also incorporating an update check into the version info (just to show whether a newer version has been released, not auto-update), feel free to copy what I've done in `mkuser`: https://github.com/freegeek-pdx/mkuser/blob/0c990446579a66f7dcaeccffd6ead4c78e134e04/mkuser.sh#L965

But, of course, you should go meta with it and use `jpt` itself to parse the JSON from the GitHub releases API!

**Comment by brunerd** [comment]
Hey @dan-snelson so `-v` and `-V` are already taken for inline and file paths to values for `-o` operations and I use getopts which only uses single letters, so to use `--version` I'd have to make a new argument handling routine...

As a workaround one could do this to get the version:
```
% jpt -h 2>/dev/stdout | head -n 1 | awk -F"[()]" '{print $2}'
v1.0.0
```
The help comes out on stderr, we shunt that to stdout, grab the first line with head and then awk out the version string. I really don't intend to do many updates on `jpt` apart from bug fixes. Features and flags are about as crowded as I want them to be. The most I am expecting is to rebuild the JSONPath parsing routines once it becomes a non-draft RFC.

Thanks for the pointer @PicoMitchell I'll keep that in mind. Although I think I'll just keep Internet reaching routines out of jpt for now to keep it simple and with less possibility of some undreamt-of exploit coming out of it! If i did though I'd use jpt vs JXA to get the value, since jpt can also run on *nixes with jsc.

Here's the JXA thought to check versions though:
```
% OSASCRIPT_ENV_JSON="$(curl -m 5 -sL 'https://api.github.com/repos/brunerd/jpt/releases/latest' 2> /dev/null)" osascript -l 'JavaScript' -e 'JSON.parse($.NSProcessInfo.processInfo.environment.objectForKey("OSASCRIPT_ENV_JSON").js).tag_name' 2> /dev/null
v1.0.0
```
Or the jpt based way:
```
% curl -m 5 -sL 'https://api.github.com/repos/brunerd/jpt/releases/latest' 2> /dev/null | jpt -T $..tag_name 
v1.0.0
```
Speaking of JXA, if I never blog about it let me just say that I've built a JXA based jpt and on a 1GB test JSON file (synthetic Jamf Computer search results) is it **massively** slower taking 37s to parse vs. jsc takes 8s and jq comes in with a sleep inducing 1m38s!

Anyway - yeah, don't worry about versions too much. Not saying jpt is without bugs but the critical updates should be few and far between.

**Comment by brunerd** [comment]
Ya know I never closed this, but thought I'd also mention besides `-h` having the version, now when without any input it will also output a short help with version.

```
% jpt
jpt (v1.0.3) - JSON Power Tool (https://github.com/brunerd/jpt)
Usage: jpt [options] [query] [filepath] (see jpt -h for more help...)
```
