### ISSUE TITLE
SyntaxError: Malformed path expression, but it works in Postgres

### ISSUE THREAD

**Issue by doekman** [brunerd/jpt#2]
When I run the command:

    jpt $'$.computer_application_usage[*] ? (@.apps[*].name == "Microsoft Outlook.app").date' < data.json

with this [data.json.zip](https://github.com/brunerd/jpt/files/11029463/data.json.zip), I get the error:

    Error: SyntaxError: Malformed path expression: $.computer_application_usage[*] ? (@.apps[*].name == "Microsoft Outlook.app").date

However, when I run the same jsonpath query in Postgres, I don't get an error. 

    select jsonb_path_query('{"computer_application_usage":[{"date":"2023/03/20","apps":[{"name":"Notes.app","version":"4.10","foreground":21,"open":0},{"name":"Safari.app","version":"16.3","foreground":9,"open":0}]},{"date":"2023/03/19","apps":[{"name":"Microsoft Excel.app","version":"16.71.23031200","foreground":2,"open":0},{"name":"Microsoft Outlook.app","version":"16.71.23031200","foreground":1,"open":0},{"name":"Microsoft Word.app","version":"16.71.23031200","foreground":1,"open":0}]},{"date":"2023/03/16","apps":[{"name":"Mail.app","version":"16.0","foreground":2,"open":0}]}]}'
    ,     '$.computer_application_usage[*] ? (@.apps[*].name == "Microsoft Outlook.app").date')
    ;

Not too sure if the query is the problem or if it might be a bug...

**Comment by brunerd** [comment]
Pardon the delay @doekman!  I don't know how I missed this... but that syntax is def not standard JSONPath. It must be Postgres specific. One of the reasons they are trying to standardize JSONPath. Even in the [new draft spec](https://datatracker.ietf.org/doc/draft-ietf-jsonpath-base/) there's no `?` joiner action like it is doing there… so you'll have to skin the cat another way (which you surely have since this is from back in March. Again sorry to have missed this.
