### ISSUE TITLE
Integrating the project in a script opened with CodeRunner

### ISSUE THREAD

**Issue by FranckSartori** [brunerd/jpt#3]
Hi. 
I would like to integrate jpt (minimized) in an existing script.
My code editor is CodeRunner on Mac.
I can paste the project in the script but then, it's like the function has an error so the functions browser of CodeRunner stops after jpt.
If I remove the locations=( [...] fi part at the end, the functions browser does not stop after jpt.
I have also opened a support request with CodeRunner but maybe someone here already has a solution.
Thanks !
Franck

**Comment by brunerd** [comment]
Hi @FranckSartori, I downloaded the latest CodeRunner (4.2.2.), pasted the [minimized jpt](https://github.com/brunerd/jpt/blob/main/sources/jpt.min) function as-is and a very simple one liner `echo '["wow"]' | jpt -T` and it's able to run in CodeRunner just fine? Nothing is halting. Make sure you are using the latest jpt v1.0.8 perhaps? Otherwise maybe there's _something else_ in your script causing this error, shell is notorious for one character causing issues way down the line. Have you simply made a script with just the jpt.min function inside? Kinda like my example here...

<img width="1244" alt="Screenshot 2023-10-05 at 12 29 26 PM" src="https://github.com/brunerd/jpt/assets/9872375/97a6c074-8d39-4cea-a677-3e7f3ac524b0">
<img width="1244" alt="Screenshot 2023-10-05 at 12 29 30 PM" src="https://github.com/brunerd/jpt/assets/9872375/26fa8404-52d9-4985-8277-d75042de6945">

**Comment by FranckSartori** [comment]
Hi Joel.
Thanks for your message.
jpt is working perfectly in CodeRunner.
The issue is that if you add a function after jpt in the script, you will not be able to navigate between the functions via the browser on the lower right corner (screenshot).
I have scripts around 35,000 lines with dozens of functions and I never saw the issue before pasting jpt (minimized or not).
If you remove the locations part at the end of jpt, the browser is available again.
I fear that CodeRunner will just tell me that the issue is in the pasted script as I can’t reproduce the issue without jpt.
I can circumvent the issue by putting jpt after the last function, but ok, that is just hiding the dust.
I didn’t find what to change in the locations part so CodeRunner behaves normally.
Such issue happens normally only if there is a syntax error in the function.
Franck
<img width="1986" alt="Capture d’écran 2023-10-05 à 20 02 30" src="https://github.com/brunerd/jpt/assets/4460512/b89eb007-15f8-4c5b-9496-51dd3e528a4f">

**Comment by brunerd** [comment]
Ah... I see... yeah it appears CodeRunner just can't deal with `case` statements where the "list" of commands is right after the "pattern" `)`. I bet they'll be able to fix that. Here's a simplified example you can use:

```
#!/bin/bash

function top()(
	echo top
)

function middle()(
	while getopts ":a" option; do 
		case "${option}" in 
			#codeRunner is flummoxed by this
			#it wants a newline after *)
			*)options+="${option}";;
		esac
	done
)

function end()(
	echo end
)
```

<img width="631" alt="no_newline" src="https://github.com/brunerd/jpt/assets/9872375/8dd82c66-9e6f-4819-b2a8-4a9caff4ffbe">
<img width="639" alt="newline" src="https://github.com/brunerd/jpt/assets/9872375/fd10a8b4-56f2-418b-9167-8fee8cf308b3">

**Comment by FranckSartori** [comment]
Thanks. I forwarded the thread to CodeRunner support. I hope they will like to improve the product to manage this situation !
